In [1]:
### 指定輸入參數
maximum_feed_rate = 48000 #最大進給速率, mm/min
motor_max_speed = 4000 #馬達最高轉速，預設3000 rpm
acceleration = "" #加速度
reduction_ratio = 1 #減速比
load = 775 #負載
cutting_force = 343 #切削力
length = 924 # 螺桿長度，兩端軸承間距
preload_rate = 0.05 #預壓率
axis = ["x", "y", "z"]
gravity_axis_YN = True #判斷重力軸
guide = maximum_feed_rate / (motor_max_speed * reduction_ratio)
N = maximum_feed_rate / guide #螺桿最高轉速

In [2]:
from math import pi

# 導程 & 最大轉速，最大進給速率 = 導程 * 最大轉速 * 減速比
guide = maximum_feed_rate / (motor_max_speed * reduction_ratio) #導程

def Diameter_calculation():
    Nm = (maximum_feed_rate / guide) * 0.5 #臨界轉速

    #由導螺桿臨界轉速估算導螺桿桿徑
    f = [9.7, 15.1, 21.9, 3.4] #[支-支, 固-支, 固-固, 固-自]
    dr_n = round((Nm * length**2 / f[2]) * 1e-7, 0) # dr = (n * (length**2) / f) * (10**-7)

    #由挫曲負荷估算導螺桿桿徑
    if gravity_axis_YN:
        p = (load + cutting_force) * 2
    else:
       cof = 0.008 #摩擦力係數
       ff = load * cof 
       p = (cutting_force + ff) * 2
    E = 21000 #kgf/mm2
    n = [4.0, 2.0, 0.25] #[固-支, 固-固, 固-自]
    dr_p = round((p * 64 * (length**2) / (n[0] * (pi**3) * E))**0.25, 0)
    #取大值
    print(f"由挫曲負荷估算導螺桿桿徑: {dr_p}mm, 由導螺桿臨界轉速估算導螺桿桿徑: {dr_n}mm")
    dr_F =  max(dr_n, dr_p)
    #由DN估算導螺桿桿徑
    dr_DN = round(150000 / N, 0)
    print(f"直徑下限: {dr_F}mm, 直徑上限: {dr_DN}mm")
    print(f"{dr_F}mm < 螺桿直徑 < {dr_DN}mm")

    d_list = [12, 14, 15, 16, 20, 25, 28, 32, 36, 40, 45, 50, 55, 63, 70, 80, 100]
    suitable_dr = []
    cunt = 0
    found_any = False
    for diameter in range(len(d_list)):
        # 同時符合強度要求 (dr_F) 且在轉速限制內 (dr_DN)
        
        if d_list[diameter] >= dr_F and d_list[diameter] <= dr_DN:
            suitable_dr.append(d_list[diameter])
            cunt = diameter
            found_any = True
    if found_any and cunt+1 < len(d_list):
        suitable_dr.append(d_list[cunt+1])
    print(suitable_dr)

    return dr_F, dr_DN, suitable_dr
dr_F, dr_DN, suitable_dr = Diameter_calculation()
print("="*100)
print(f"導程: {guide}")
print("="*100)
#def Load_calculation():

由挫曲負荷估算導螺桿桿徑: 15.0mm, 由導螺桿臨界轉速估算導螺桿桿徑: 8.0mm
直徑下限: 15.0mm, 直徑上限: 38.0mm
15.0mm < 螺桿直徑 < 38.0mm
[15, 16, 20, 25, 28, 32, 36, 40]
====================================================================================================
導程: 12.0
====================================================================================================

In [ ]:
#動負荷計算
if gravity_axis_YN:
        p = (load + cutting_force)
else:
    cof = 0.008 #摩擦力係數
    ff = load * cof 
    p = (cutting_force + ff)

c = round(p / 3 / preload_rate, 0)
print(f"動負荷: {c} kfg")

動負荷: 7453.0 kfg

In [5]:
#馬達扭矩計算
def Motor_torque_calculation(guide, load, cutting_force):
    w2 = load
    hsp = guide
    cof = 0.008
    me = 0.9
    Tt1 = (1 + cof) * hsp * w2 / (2 * pi * me) #kgf*mm
    Tt2 = abs((1 - cof) * hsp * w2 / (2 * pi * me)) #kgf*mm
    Tt = round(max(Tt1, Tt2) * 9.8 * 1e-3, 2) #N*m
    
    fc = cutting_force
    Tc = round((fc * hsp * me) / (2*pi)* 9.8 * 1e-3, 2) #N*m

    Trf = Tc + Tt
    print(f"移動件所引起的摩擦扭矩: {Tt} N．mm, 軸向力引起的扭矩:{Tc} N．mm")
    print(f"外加負荷引起之扭矩: {Trf} N．mm")
    return Trf

#馬達慣量計算
def Motor_inertia_calculation(length, suitable_dr, load, guide):
    proportion = 0.0078
    L = length
    g = 980
    Js = pi * proportion * (L* 0.1 )* ((suitable_dr[-1]*0.1)**4) / (32* g ) # kgf*cm*s**2
    W = load
    hsp = guide*0.1
    Jt = W / g * (hsp / 2 / pi)**2 #增加減速比考慮
    JL = round(Js + Jt, 4)
    print(f"負載慣量: {JL} kgf．cm．s2")
    return JL
Trf = Motor_torque_calculation(guide, load, cutting_force)
print("=" *100)
JL = Motor_inertia_calculation(length, suitable_dr, load, guide)

移動件所引起的摩擦扭矩: 16.25 N．mm, 軸向力引起的扭矩:5.78 N．mm
外加負荷引起之扭矩: 22.03 N．mm
====================================================================================================
負載慣量: 0.0473 kgf．cm．s2

In [ ]:
from img2table.document import PDF
from img2table.ocr import PaddleOCR
import warnings
import os

# 1. 忽略所有 UserWarning (包含 ccache 的提示)
warnings.filterwarnings("ignore", category = UserWarning)


paddle_ocr = PaddleOCR(lang="ch", kw={"use_angle_cls": True})

pdf = PDF(src = R"C:\Users\e11338\Downloads\上銀滾珠螺桿 預壓0.3.pdf")

extracted_tables = pdf.extract_tables(
    ocr = paddle_ocr, # 或 tesseract
    implicit_rows = True,         # [重要] 即使沒橫線也能根據文字對齊判斷行
    implicit_columns = True,      # [重要] 自動判斷縱向對齊，防止數據跑位
    borderless_tables = True,     # [重要] 偵測那些線條較細或不完整的邊框
    min_confidence = 30           # 調低信心門檻，先抓到資料，後續再用 Python 清洗
)

# for page, tables in extracted_tables.items():
#     for table in tables:
#         # 將結果轉為 pandas DataFrame 方便處理
#         df = table.df
#         print(f"Page {page} Table:")
#         display(df)

first_df = list(extracted_tables.values())[0][-1].df

# 印出結果
display(first_df)

In [3]:
import pandas as pd
import camelot

# 1. pages='all' 會抓取 PDF 內所有偵測到的表格 
tables = camelot.read_pdf(R"C:\Users\e11338\Downloads\上銀滾珠螺桿 預壓0.3.pdf", 
                          flavor='lattice', 
                          process_background=True,
                          line_scale=40,
                          pages='all')

print(f"總共偵測到 {len(tables)} 個表格區塊")

# 2. 合併所有表格 
# 注意：上銀型錄每頁的欄位結構可能略有不同（例如 FSV 與 FSI 型），
# 建議先檢查欄位數量是否一致再合併。
all_dfs = [t.df for t in tables]
full_df = pd.concat(all_dfs, ignore_index=True)

# 3. 顯示前 50 行檢查 
display(full_df.head(50))

總共偵測到 45 個表格區塊

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,S \nT,,,,,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Z,ØX,,,,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,,,,,,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ØDg6,ØD -0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,型號,規格,,珠徑,PCD,根徑,珠卷數,剛性\nKgf /μm\nK,動負荷\nC ( kgf ),靜負荷\nCo ( kgf ),...,迴流管,,法蘭孔,,,接觸\n面長,NaN,NaN,NaN,NaN
5,,公稱\n外徑,導程,,,,,,,,...,W,H,X\nY,,Z,S,NaN,NaN,NaN,NaN
6,16-4B2,16,4,2.381,16.25,13.792,2.5x2,26,802,1722,...,23,21,5.5,9.5,5.5,12,NaN,NaN,NaN,NaN
7,16-5B1,,5,3.175,16.6,13.324,2.5x1,16,763\n1400,,...,27,22,5.5,9.5,5.5,12,NaN,NaN,NaN,NaN
8,16-5B2,,,,16.6,13.324,2.5x2,33,1385\n2799,,...,27,22,5.5,9.5,5.5,12,NaN,NaN,NaN,NaN
9,16-5C1,,,,16.6,13.324,3.5x1,22,1013,1946,...,27,22,5.5,9.5,5.5,12,NaN,NaN,NaN,NaN
10,16-10B1,,10,,16.6,13.324,2.5x1,16,763,1399,...,22.5,23,5.5,9.5,5.5,12,NaN,NaN,NaN,NaN
11,20-5B1,20,5,,20.6,17.324,2.5x1,19,837,1733,...,27,25,5.5,9.5,5.5,12,NaN,NaN,NaN,NaN
12,20-5B2,,,,20.6,17.324,2.5x2,39,1519,3465,...,27,25,5.5,9.5,5.5,12,NaN,NaN,NaN,NaN
13,20-6B1,,6,3.969,20.8,16.744,2.5x1,20,1139,2187,...,28,27,5.5,9.5,5.5,12,NaN,NaN,NaN,NaN
14,20-6C1,,,,20.8,16.744,3.5x1,28,1512,3041,...,28,27,5.5,9.5,5.5,12,NaN,NaN,NaN,NaN
15,20-20A1,,20,,20.8,16.744,1.5x1,13,719,1281,...,28,27,5.5,9.5,5.5,12,NaN,NaN,NaN,NaN
16,25-5B2,25,5,3.175,25.6,22.324,2.5x2,46,1704,4417,...,31,26,5.5,9.5,5.5,12,NaN,NaN,NaN,NaN
17,25-5C1,,,,25.6,22.324,3.5x1,35,1252,3085,...,31,26,5.5,9.5,5.5,12,NaN,NaN,NaN,NaN
18,25-6B2,,6,3.969,25.8,21.744,2.5x2,48,2308,5523,...,32,28,6.6,11,6.5,12,NaN,NaN,NaN,NaN
19,25-6C1,,,,25.8,21.744,3.5x1,35,1690,3844,...,32,28,6.6,11,6.5,12,NaN,NaN,NaN,NaN
20,25-8B2,,8,4.763,26,21.132,2.5x2,46,2888,6472,...,35,31,5.5,9.5,5.5,15,NaN,NaN,NaN,NaN
21,25-10B1,,10,,26,21.132,2.5x1,25,1592,3237,...,34,29,6.6,11,6.5,12,NaN,NaN,NaN,NaN
22,25-10B2,,,,26,21.132,2.5x2,46,2888,6472,...,35,31,6.6,11,6.5,15,NaN,NaN,NaN,NaN
23,25-16B1,,16,,26,21.132,2.5x1,28,1592,3237,...,34,29,6.6,11,6.5,12,NaN,NaN,NaN,NaN
24,25-20B1,,20,,26,21.132,2.5x1,28,1592,3237,...,34,29,6.6,11,6.5,12,NaN,NaN,NaN,NaN
25,25-25A1,,25,,26,21.132,1.5x1,16,1019,1927,...,34,29,6.6,11,6.5,12,NaN,NaN,NaN,NaN
26,28-5B1,28,5,3.175,28.6,25.324,2.5x1,26,984,2466,...,34,28,6.6,11,6.5,12,NaN,NaN,NaN,NaN
27,28-5B2,,,,28.6,25.324,2.5x2,50,1785,4932,...,34,28,6.6,11,6.5,12,NaN,NaN,NaN,NaN
28,28-6A2,,6,,28.6,25.324,1.5x2,29,1150,2960,...,34,28,6.6,11,6.5,12,NaN,NaN,NaN,NaN
29,28-6B2,,,,28.6,25.324,2.5x2,48,1784,4932,...,36,29,6.6,11,6.5,15,NaN,NaN,NaN,NaN
30,32-5B2,32,5,,32.6,29.324,2.5x2,55,1886,5666,...,38,30,6.6,11,6.5,12,NaN,NaN,NaN,NaN
31,32-5C1,,,,32.6,29.324,3.5x1,39,1388,3967,...,38,30,6.6,11,6.5,12,NaN,NaN,NaN,NaN
32,32-6B2,,6,3.969,32.8,28.744,2.5x2,56,2556,7020,...,39,32,6.6,11,6.5,12,NaN,NaN,NaN,NaN
33,32-6C1,,,,32.8,28.744,3.5x1,39,1888,4936,...,39,32,6.6,11,6.5,12,NaN,NaN,NaN,NaN
34,32-8B2,,8,4.763,33,28.132,2.5x2,59,3284,8453,...,40,33,9,14,8.5,15,NaN,NaN,NaN,NaN
35,32-8C1,,,,33,28.132,3.5x1,41,2428,5948,...,40,33,9,14,8.5,15,NaN,NaN,NaN,NaN
36,32-10B1,,10,6.350,33.4,26.91,2.5x1,30,2650,5599,...,44,37,9,14,8.5,15,NaN,NaN,NaN,NaN
37,32-10B2,,,,33.4,26.91,2.5x2,60,4810,11199,...,44,37,9,14,8.5,15,NaN,NaN,NaN,NaN
38,32-10C1,,,,33.4,26.91,3.5x1,44,3519,7785,...,44,37,9,14,8.5,15,NaN,NaN,NaN,NaN
39,32-16B1,,16,,33.4,26.91,2.5x1,30,2650,5599,...,45,38,9,14,8.5,15,NaN,NaN,NaN,NaN
40,32-20B1,,20,4.763,33,28.132,2.5x1,33,1810,4227,...,40,33,9,14,8.5,15,NaN,NaN,NaN,NaN
41,32-25B1,,25,,33,28.132,2.5x1,33,1810,4227,...,40,33,9,14,8.5,15,NaN,NaN,NaN,NaN
42,32-32A1,,32,,33,28.132,1.5x1,18,1154,2505,...,40,33,9,14,8.5,15,NaN,NaN,NaN,NaN
43,36-6B1,36,6,3.969,36.8,32.744,2.5x1,35,1486,3969,...,42,32,6.6,11,6.5,12,NaN,NaN,NaN,NaN
44,36-6B2,,,,36.8,32.744,2.5x2,60,2696,7937,...,42,32,6.6,11,6.5,12,NaN,NaN,NaN,NaN
45,S \nT,,,,,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Z,ØX,,,,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,,,,,,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
import pandas as pd
#display(tables[44].df)
page = [2, 6, 10, 13, 16, 19, 23, 27, 31, 36, 40, 42, 44]
idx_list = []
for i in range(len(tables)):
    if len(tables[i].df) > 10:
        idx_list.append(i)

print(idx_list, len(idx_list))
for i in idx_list:
    print(len(tables[i].df))
    display(tables[i].df.head())

#len(page)
#tables[2].to_excel(R"C:\Users\e11338\Desktop\Feed System GAI\test_table.xlsx", sheet_name='Sheet1', index=True)

[2, 6, 10, 13, 16, 19, 23, 27, 31, 36, 40, 41, 42, 43, 44] 15
41

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,型號,規格,,珠徑,PCD,根徑,珠卷數,剛性\nKgf /μm\nK,動負荷\nC ( kgf ),靜負荷\nCo ( kgf ),...,,法蘭,,,迴流管,,法蘭孔,,,接觸\n面長
1,,公稱\n外徑,導程,,,,,,,,...,L,F,T\nBCD-E,,W,H,X\nY,,Z,S
2,16-4B2,16,4,2.381,16.25,13.792,2.5x2,26,802,1722,...,48,52,10\n40,,23,21,5.5,9.5,5.5,12
3,16-5B1,,5,3.175,16.6,13.324,2.5x1,16,763\n1400,,...,45,54,12\n41,,27,22,5.5,9.5,5.5,12
4,16-5B2,,,,16.6,13.324,2.5x2,33,1385\n2799,,...,60,54,12\n41,,27,22,5.5,9.5,5.5,12

41

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,型號,規格,,珠徑,PCD,根徑,珠卷數,剛性\nKgf /μm\nK,動負荷\nC ( kgf ),靜負荷\nCo ( kgf ),...,,法蘭,,,迴流管,,法蘭孔,,,接觸\n面長
1,,公稱\n外徑,導程,,,,,,,,...,L,F\nT,,BCD-E,W\nH,,X\nY,,Z,S
2,36-10B2,36,10,6.350,37.4,30.91,2.5x2,68,5105,12669,...,102,104,18,82\n49,,40,11,17.5,11,15
3,40-5B2,40,5,3.175,40.6,37.324,2.5x2\n66,,2071,7134,...,65,92,16,72\n46,,34,9,14,8.5,15
4,40-6B2,,6,3.969,40.8,36.744,2.5x2\n69,,2817,8855,...,72,94,16,76\n47,,36,9,14,8.5,15

21

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,型號,規格,,珠徑,PCD,根徑,珠卷數,剛性\nKgf /μm\nK,動負荷\nC ( kgf ),靜負荷\nCo ( kgf ),...,,法蘭,,,迴流管,,法蘭孔,,,接觸\n面長
1,,公稱\n導程\n外徑,,,,,,,,,...,L,F,T,BCD-E,W,H,X,Y\nZ,,S
2,63-20B3,63,20,12.700,66,53.16,2.5x3,210,30715,90887,...,244,157,32,137\n82,,70,11,17.5,11,30
3,70-10B2,70,10,6.350,71.4,64.91,2.5x2,115,6843,25011,...,109,152,20,128\n80,,56,13,20,13,20
4,70-10B3,,,,71.4,64.91,2.5x3,170,9688,37516,...,139,152,20,128\n80,,56,13,20,13,20

40

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,型號,規格,,珠徑,PCD,根徑,珠卷數,剛性\nKgf /μm\nK,動負荷\nC ( kgf ),靜負荷\nCo ( kgf ),螺帽,,法蘭,,,法蘭孔,,,接觸\n面長
1,,公稱\n外徑,導程,,,,,,,,D\nL,,F,T\nBCD-E,,X,Y\nZ,,S
2,12-4B1,12,4,2.381,12.25,9.792,2.5x1,8,383,638,30,38,50,10,40,4.5,8,4\n12,
3,12-4C1,,,,12.25,9.792,3.5x1,9,511,893,30,44,50,10,40,4.5,8,4\n12,
4,12-5B1,,5,,12.25,9.792,2.5x1,8,383,638,30,40,50,10,40,4.5,8,4\n12,

39

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,型號,規格,,珠徑,PCD,根徑,珠卷數,剛性\nKgf /μm\nK,動負荷\nC ( kgf ),靜負荷\nCo ( kgf ),螺帽,,法蘭,,,法蘭孔,,,接觸\n面長
1,,公稱\n外徑,導程,,,,,,,,D\nL,,F,T,BCD-E,X\nY,,Z,S
2,32-16A2,32,16,6.350,33.4,26.91,1.5x2,36,3035,6555,74,99,108,16,90,9,14,8.5\n15,
3,32-16B1,,,,33.4,26.91,2.5x1\n30,,2650,5599,74,94,108,16,90,9,14,8.5\n15,
4,32-16B2,,,,33.4,26.91,2.5x2\n59,,4810,11199,74,130,108,16,90,9,14,8.5\n15,

31

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,型號,規格,,珠徑,PCD,根徑,珠卷數,剛性\nKgf /μm\nK,動負荷\nC ( kgf ),靜負荷\nCo ( kgf ),螺帽,,法蘭,,,法蘭孔,,,接觸\n面長
1,,公稱\n外徑,導程,,,,,,,,D,L,F,T\nBCD-E,,X,Y\nZ,,S
2,55-10B2,55,10,6.350,56.4,49.91,2.5x2,93,6071,19592,102,103,144,18\n122,,11,17.5,11,20
3,55-10C1,,,,56.4,49.91,3.5x1,66,4562,13661,100,84,140,18\n118,,11,17.5,11,20
4,55-12B2,,12,7.938,56.8,48.688,2.5x2,95,8392,24390,105,123,154,22\n127,,13,20,13,20

33

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,型號,規格,,珠徑,PCD,根徑,珠卷數,剛性\nKgf /μm\nK,動負荷\nC ( kgf ),靜負荷\nCo ( kgf ),螺帽,,法蘭,,,法蘭孔,,,接觸\n面長
1,,公稱\n外徑,導程,,,,,,,,D\nL,,F,T\nBCD-E,,X,Y,Z,S
2,8-2.5T3,8,2.5,1.500,8.2,6.652,3,8,170,267,18,28,35,5,27,4.5,0,0,0
3,14-2.54T3,14,2.54,2.000,14.2,12.136,3,12,339,655,30,39,50,10.6,40,5,7,5,0
4,14-4T3,,4,,14.2,12.136,3,12,339,655,26,33,48,6,36,5.5,0,0,0

33

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,型號,規格,,珠徑,PCD,根徑,珠卷數,剛性\nKgf /μm\nK,動負荷\nC ( kgf ),靜負荷\nCo ( kgf ),螺帽,,,法蘭,,,法蘭孔,,,接觸\n面長
1,,公稱\n外徑,導程,,,,,,,,D,,L,F,T\nBCD-E,,X,Y,Z,S
2,32-5T3,32,5,3.175,32.6,29.324,3,33,1117,3081,44,48,46,74,12,60,6.6,11,6.5,12
3,32-5T4,,,,32.6\n29.324,,4,42,1431,4108,44,48,53,74,12,60,6.6,11,6.5,12
4,32-5T6,,,,32.6\n29.324,,6,63,2027,6162,44,48,66,74,12,60,6.6,11,6.5,12

23

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,型號,規格,,珠徑,PCD,根徑,珠卷數,剛性\nKgf /μm\nK,動負荷\nC ( kgf ),靜負荷\nCo ( kgf ),螺帽,,,法蘭,,,法蘭孔,,,接觸\n面長
1,,公稱\n外徑,導程,,,,,,,,D\nL,,,F,T\nBCD-E,,X\nY,,Z,S
2,63-6T4,63,6,3.969,63.8,59.744,4,75,2614,10542,78,80,66,119,18,98,11,17.5,11,20
3,63-6T6,,,,63.8,59.744,6,113,3704,15813,78,80,81,119,18,98,11,17.5,11,20
4,63-8T4,,8,4.763,64,59.132,4,77,3395,12541,79,82,80,122,18,100,11,17.5,11,20

39

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,型號,規格,,珠徑,PCD,根徑,珠卷數,剛性\nKgf /μm\nK,動負荷\nC ( kgf ),靜負荷\nCo ( kgf ),螺帽,,,鍵槽,,,
1,,公稱\n外徑,導程,,,,,,,,D\nL,,,K,W\nH,,K1
2,16-2T4,16,2,1.500,16.2,14.652,4,15,178,395,25,25,25,20,3,1.8,2.5
3,16-5T3,,5,3.175,16.6,13.324,3,11,731,1331,28,30,40,20,3,1.8,10
4,16-5T4,,,,16.6,13.324,4,12,936,1775,28,30,46,20,3,1.8,13

26

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,型號,規格,,珠徑,PCD,根徑,珠卷數,剛性\nKgf /μm\nK,動負荷\nC ( kgf ),靜負荷\nCo ( kgf ),螺帽,,,鍵槽,,,
1,,公稱\n導程\n外徑,,,,,,,,,D\nL,,,K,W\nH,,K1
2,50-10T6,50,12,6.350,51.4,44.91,6,94,6165,18511,69,74,102,40,6,3.5,31
3,50-12T3,,,7.938,51.8,43.688,3,50,4420,11047,73,78,82,40,6,3.5,21
4,50-12T4,,,,51.8,43.688,4,63,5660,14730,73,78,95,40,6,3.5,27.5

21

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,D6\nForm A\nTYPE 1\nTYPE 2\nL2\nM\n22.5°\n30°\...,,,,,,,,,,,,,,,,
1,,,,,,,,,,,,,,,,,
2,,,,,,L7\nL1,,,,,,,,D6,,,
3,,,,,,L11,,,,,,,,,,,
4,,,,,,,,,,,,,,,,,

64

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,型號,規格,,節圓\n直徑,,根徑 珠徑,卷數,剛性 K\n(kgf/μm),動負荷\nC(kgf),靜負荷\nCo(kgf),...,,,,,,油孔,,,雙牙,不出牙
1,,公稱\n外徑,導程,,,,,,,,...,Form \nB (L8),Form \nC (L9),L7,D4,D5,M,,L10 L11,,
2,14-10K3,14,10,14.6,10.724,3.175,3,24,920,1790,...,40,44,,38\n45,,,6,5,,
3,15-10K3,15,10,16,12.869,3,3,26,930,1970,...,,,,,,,,,,
4,15-16K2,,16,,,,2,16,610,1230,...,,,,,,,,,,

21

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,D6\nForm A\nTYPE 1\nTYPE 2\nL2\nM\n22.5°\n30°\...,,,,,,,,,,,,,,,,
1,,,,,,,,,,,,,,,,,
2,,,,,,L7\nL1,,,,,,,,D6,,,
3,,,,,,L11,,,,,,,,,,,
4,,,,,,,,,,,,,,,,,

61

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,型號,規格,,節圓\n直徑,根徑,珠徑,卷數,剛性 K\n(kgf/μm),動負荷\nC(kgf),靜負荷\nCo(kgf),...,,,,,,油孔,,,雙牙,不出牙
1,,公稱\n外徑,導程,,,,,,,,...,Form \nB (L8),Form \nC (L9),L7,D4,D5,M,L10,L11,,
2,40-5K5,40,5,40.6,37.324,3.175,5,85,2470,9490,...,70,81.5,14,78,9,,,7,,
3,40-6K5,,6,40.8,36.744,3.969,5,95,3370,11780,...,,,,,,,,,,
4,40-8K5,,8,41,36.132,4.763,5,101,4360,14200,...,,,,,,,,,,●

In [187]:
import numpy as np
page = [2, 6, 10, 13, 16, 19, 23, 27, 31, 36, 40, 42, 44]
type = ["FSV", "FSI", "RSI", "FSC"]
pages = [6, 3, 2, 2 ]

def Data_cleanong(tables):
    cols_name = ["型號", "公稱 外徑", "導程", "珠徑", "PCD", "根徑", "珠卷數", "剛性 kfg/umk", "動負荷 C (kfg)", "靜負荷 Co (kfg)"]
    df = tables.df[2:]
    df = df.iloc[:, :10]
    df.columns = cols_name

        
    def split_all_merged_cells(df):
        # 建立一個副本，避免更動原始數據
        new_df = df.copy()
        
        # 遍歷每一列
        for index, row in new_df.iterrows():
            # 遍歷每一欄 (除了最後一欄，因為最後一欄沒人可以推擠)
            rows_count = len(new_df)
            cols_count = len(new_df.columns)
        for r in range(rows_count):
            for c in range(cols_count - 1): # 到倒數第二欄為止
                cell_val = new_df.iat[r, c]
                
                if '\n' in cell_val:
                    parts = cell_val.split('\n')
                    # 前半段留在原地
                    new_df.iat[r, c] = parts[0].strip()
                    # 後半段推擠到右邊那格
                    # 注意：如果右邊原本有值且非空白，這會覆蓋它。
                    # 但在上銀型錄中，被合併的右邊通常是空的。
                    new_df.iat[r, c + 1] = parts[1].strip()
                    
        return new_df

    df = split_all_merged_cells(df)
    df = df.replace(r'^\s*$', np.nan, regex=True)
    df = df.ffill()
    col = ["公稱 外徑", "導程", "動負荷 C (kfg)"]
    for col in col:
        df[col] = pd.to_numeric(df[col], errors='coerce')
    return df

df = Data_cleanong(tables[36])
df
#df.to_excel(R"C:\Users\e11338\Desktop\Feed System GAI\test_table.xlsx", sheet_name='Sheet1', index=True)

,型號,公稱 外徑,導程,珠徑,PCD,根徑,珠卷數,剛性 kfg/umk,動負荷 C (kfg),靜負荷 Co (kfg)
2,16-2T4,16,2,1.500,16.2,14.652,4,15,178,395
3,16-5T3,16,5,3.175,16.6,13.324,3,11,731,1331
4,16-5T4,16,5,3.175,16.6,13.324,4,12,936,1775
5,20-5T3,20,5,3.175,20.6,17.324,3,20,852,1767
6,20-5T4,20,5,3.175,20.6,17.324,4,27,1091,2356
7,20-6T3,20,6,3.969,20.8,16.744,3,20,1091,2081
8,20-6T4,20,6,3.969,20.8,16.744,4,27,1398,2774
9,25-5T3,25,5,3.175,25.6,22.324,3,28,977,2314
10,25-5T4,25,5,3.175,25.6,22.324,4,37,1252,3085
11,25-6T3,25,6,3.969,25.8,21.744,3,28,1272,2762
12,25-6T4,25,6,3.969,25.8,21.744,4,37,1628,3682
13,32-5T3,32,5,3.175,32.6,29.324,3,33,1117,3081
14,32-5T4,32,5,3.175,32.6,29.324,4,42,1431,4108
15,32-5T6,32,5,3.175,32.6,29.324,6,63,2027,6162
16,32-6T3,32,6,3.969,32.8,28.744,3,33,1446,3620
17,32-6T4,32,6,3.969,32.8,28.744,4,43,1852,4826
18,32-6T6,32,6,3.969,32.8,28.744,6,65,2625,7239
19,32-8T3,32,8,4.763,33,28.132,3,35,1810,4227
20,32-8T4,32,8,4.763,33,28.132,4,47,2317,5635
21,32-10T3,32,10,6.350,33.4,26.91,3,35,2539,5327
22,32-10T4,32,10,6.350,33.4,26.91,4,48,3252,7102
23,40-5T4,40,5,3.175,40.6,37.324,4,50,1599,5280
24,40-5T6,40,5,3.175,40.6,37.324,6,74,2265,7919
25,40-6T4,40,6,3.969,40.8,36.744,4,50,2136,6420
26,40-6T6,40,6,3.969,40.8,36.744,6,74,3028,9630
27,40-8T4,40,8,4.763,41,36.132,4,52,2728,7596
28,40-8T6,40,8,4.763,41,36.132,6,76,3866,11394
29,40-10T3,40,10,6.350,41.4,34.91,3,40,2959,7069
30,40-10T4,40,10,6.350,41.4,34.91,4,51,3789,9426
31,50-5T4,50,5,3.175,50.6,47.324,4,62,1757,6745
32,50-5T6,50,5,3.175,50.6,47.324,6,91,2490,10117
33,50-6T4,50,6,3.969,50.8,46.744,4,62,2388,8250
34,50-6T6,50,6,3.969,50.8,46.744,6,93,3384,12375
35,50-8T4,50,8,4.763,51,46.132,4,62,2998,9578
36,50-8T6,50,8,4.763,51,46.132,6,92,4249,14367
37,50-10T3,50,10,6.350,51.4,44.91,3,50,3397,9256
38,50-10T4,50,10,6.350,51.4,44.91,4,63,4350,12341\n69

In [202]:
page = [2, 6, 10, 13, 16, 19, 23, 27, 31, 36, 40]
type = ["FSV", "FSI", "RSI"]
group = [6, 3, 2]
conact = []
file_path = Rf"C:\Users\e11338\Desktop\Feed System GAI\HIWIN_Specs.xlsx"

with pd.ExcelWriter(file_path, engine='xlsxwriter') as writer:
    for idx, i in enumerate(group):
        conact = []
        for j in range(i):
            df = Data_cleanong(tables[page[j]])
            conact.append(df)
        # print(conact)
        # for i in range(10):
        #     print()
        df_conat = pd.concat(conact)
        globals()[f"{type[idx]}"] = df_conat
        globals()[f"{type[idx]}"].to_excel(writer, sheet_name = f"{type[idx]}", index=False)
        page = page[j+1:]